from typing import List, Dict, Any

# Estado mockado em memória, compartilhado entre MockFuncionarioProvider e
# MockAdminProvider para que as telas de funcionário e de administração
# reflitam exatamente os mesmos agendamentos durante a execução da aplicação.
MOCK_AGENDAMENTOS: List[Dict[str, Any]] = [
    {
        "id": 1,
        "nome": "Maria Silva Souza",
        "prontuario": "123456-7",
        "exames": ["Ecocardiograma Transtorácico", "Eletrocardiograma (ECG)"],
        "diasNaFila": 15,
        "status": "ALTA",
        "unidadeExecutora": "Unidade de Cardiologia",
        "unidadeSolicitante": "Ambulatório de Cardiologia Geral",
        "dataRetorno": "28/06/2026",
        "localizacao": "Recife",
        "regiao": "I Regional de Saúde",
        "idade": 72,
        "atendente": None,
        "estado": None,
        "resultado": None,
        "problema_motivo": None,
    },
    {
        "id": 2,
        "nome": "Pedro Henrique Ramos",
        "prontuario": "765432-1",
        "exames": ["Ultrassonografia Abdominal Total"],
        "diasNaFila": 5,
        "status": "MÉDIA",
        "unidadeExecutora": "Unidade de Diagnóstico por Imagem",
        "unidadeSolicitante": "Pediatria - Ambulatório",
        "dataRetorno": "05/07/2026",
        "localizacao": "Olinda",
        "regiao": "I Regional de Saúde",
        "idade": 8,
        "atendente": None,
        "estado": None,
        "resultado": None,
        "problema_motivo": None,
    },
    {
        "id": 3,
        "nome": "Ana Paula Medeiros",
        "prontuario": "246813-5",
        "exames": ["Hemograma Completo", "Glicemia de Jejum", "Creatinina"],
        "diasNaFila": 2,
        "status": "BAIXA",
        "unidadeExecutora": "Laboratório de Análises Clínicas",
        "unidadeSolicitante": "Ambulatório de Clínica Médica",
        "dataRetorno": "12/07/2026",
        "localizacao": "Caruaru",
        "regiao": "IV Regional de Saúde",
        "idade": 34,
        "atendente": None,
        "estado": None,
        "resultado": None,
        "problema_motivo": None,
    },
    {
        "id": 4,
        "nome": "José Carlos Oliveira",
        "prontuario": "135792-4",
        "exames": ["Ressonância Magnética de Crânio"],
        "diasNaFila": 30,
        "status": "BAIXA",
        "unidadeExecutora": "Unidade de Diagnóstico por Imagem",
        "unidadeSolicitante": "Neurologia - Ambulatório",
        "dataRetorno": "10/07/2026",
        "localizacao": "Petrolina",
        "regiao": "VIII Regional de Saúde",
        "idade": 67,
        "atendente": None,
        "estado": None,
        "resultado": None,
        "problema_motivo": None,
    },
    {
        "id": 5,
        "nome": "Juliana Santos Lima",
        "prontuario": "987654-3",
        "exames": ["Mamografia Bilateral"],
        "diasNaFila": 8,
        "status": "ALTA",
        "unidadeExecutora": "Centro de Oncologia - Imagem",
        "unidadeSolicitante": "Mastologia - Ambulatório",
        "dataRetorno": "01/07/2026",
        "localizacao": "Jaboatão dos Guararapes",
        "regiao": "I Regional de Saúde",
        "idade": 45,
        "atendente": None,
        "estado": None,
        "resultado": None,
        "problema_motivo": None,
    },
    {
        "id": 6,
        "nome": "Lucas Cavalcanti Farias",
        "prontuario": "543210-9",
        "exames": ["Raio-X de Tórax (PA e Perfil)"],
        "diasNaFila": 12,
        "status": "MÉDIA",
        "unidadeExecutora": "Radiologia Geral",
        "unidadeSolicitante": "Pneumologia Geral",
        "dataRetorno": "03/07/2026",
        "localizacao": "Paulista",
        "regiao": "I Regional de Saúde",
        "idade": 16,
        "atendente": None,
        "estado": None,
        "resultado": None,
        "problema_motivo": None,
    },
    # Itens pré-atribuídos, usados para popular as telas administrativas
    # (Gestão de Pendências e Gerenciamento de Agendamentos) com casos reais
    # de exemplo, sem afetar a fila geral acima.
    {
        "id": 7,
        "nome": "Roberto Almeida Castro",
        "prontuario": "154844785",
        "exames": ["Colonoscopia", "Ecocardiograma"],
        "diasNaFila": 4,
        "status": "ALTA",
        "unidadeExecutora": "Unidade de Endoscopia",
        "unidadeSolicitante": "Gastroenterologia - Ambulatório",
        "dataRetorno": "30/06/2026",
        "localizacao": "Recife",
        "regiao": "I Regional de Saúde",
        "idade": 58,
        "atendente": "fabiana.lopes",
        "estado": "EM_ANDAMENTO",
        "resultado": None,
        "problema_motivo": "Dados Inconsistentes",
        "problema_detalhes": "Esse paciente está solicitando um exame inexistente.",
    },
    {
        "id": 8,
        "nome": "Camila Ferreira Dias",
        "prontuario": "487462528",
        "exames": ["Espirometria"],
        "diasNaFila": 20,
        "status": "ALTA",
        "unidadeExecutora": "Unidade de Pneumologia",
        "unidadeSolicitante": "Pneumologia - Ambulatório",
        "dataRetorno": "02/07/2026",
        "localizacao": "Olinda",
        "regiao": "I Regional de Saúde",
        "idade": 61,
        "atendente": "joao.silva",
        "estado": "EM_ANDAMENTO",
        "resultado": None,
        "problema_motivo": None,
        "problema_detalhes": None,
    },
    {
        "id": 9,
        "nome": "Beatriz Souza Martins",
        "prontuario": "379165798",
        "exames": ["Ultrassonografia"],
        "diasNaFila": 4,
        "status": "ALTA",
        "unidadeExecutora": "Unidade de Diagnóstico por Imagem",
        "unidadeSolicitante": "Clínica Médica - Ambulatório",
        "dataRetorno": "25/06/2026",
        "localizacao": "Jaboatão dos Guararapes",
        "regiao": "I Regional de Saúde",
        "idade": 39,
        "atendente": "fabiana.lopes",
        "estado": "FINALIZADO",
        "resultado": "CONFIRMADO",
        "problema_motivo": None,
        "problema_detalhes": None,
    },
    {
        "id": 10,
        "nome": "Thiago Ramos Pereira",
        "prontuario": "197564824",
        "exames": ["Ultrassonografia"],
        "diasNaFila": 4,
        "status": "ALTA",
        "unidadeExecutora": "Unidade de Diagnóstico por Imagem",
        "unidadeSolicitante": "Clínica Médica - Ambulatório",
        "dataRetorno": "25/06/2026",
        "localizacao": "Caruaru",
        "regiao": "IV Regional de Saúde",
        "idade": 44,
        "atendente": "joao.silva",
        "estado": "FINALIZADO",
        "resultado": "CANCELADO",
        "problema_motivo": None,
        "problema_detalhes": None,
    },
]

MOCK_FUNCIONARIOS: List[Dict[str, str]] = [
    {"username": "fabiana.lopes", "nome": "Fabiana Lopes"},
    {"username": "joao.silva", "nome": "João Silva"},
    {"username": "carla.mendes", "nome": "Carla Mendes"},
    {"username": "ricardo.alves", "nome": "Ricardo Alves"},
]


def nome_funcionario(username: str | None) -> str | None:
    if not username:
        return None
    for funcionario in MOCK_FUNCIONARIOS:
        if funcionario["username"] == username:
            return funcionario["nome"]
    return username
