# Mapeamento estático de municípios de Pernambuco para suas mesorregiões.
# Fonte de referência: IBGE / PNUD (divisão regional de PE).
# As chaves estão normalizadas (sem acento, minúsculas) para facilitar a busca,
# usar _normalizar() antes de consultar para garantir coerência.

MUNICIPIO_PARA_REGIAO: dict[str, str] = {
    # Região Metropolitana 
    "recife": "Região Metropolitana",
    "olinda": "Região Metropolitana",
    "jaboatao dos guararapes": "Região Metropolitana",
    "paulista": "Região Metropolitana",
    "camarajibe": "Região Metropolitana",
    "sao lourenco da mata": "Região Metropolitana",
    "abreu e lima": "Região Metropolitana",
    "igarassu": "Região Metropolitana",
    "itapissuma": "Região Metropolitana",
    "ilha de itamaraca": "Região Metropolitana",
    "moreno": "Região Metropolitana",
    "aracoiaba": "Região Metropolitana",
    "ipojuca": "Região Metropolitana",
    "cabo de santo agostinho": "Região Metropolitana",

    # Zona da Mata 
    "palmares": "Zona da Mata",
    "rio formoso": "Zona da Mata",
    "barreiros": "Zona da Mata",
    "sao jose da coroa grande": "Zona da Mata",
    "agua preta": "Zona da Mata",
    "gameleira": "Zona da Mata",
    "catende": "Zona da Mata",
    "escada": "Zona da Mata",
    "amaraji": "Zona da Mata",
    "quipapa": "Zona da Mata",
    "cortez": "Zona da Mata",
    "ribeiro": "Zona da Mata",
    "bonito": "Zona da Mata",
    "sao benedito do sul": "Zona da Mata",
    "calcado": "Zona da Mata",
    "jurema": "Zona da Mata",
    "jucati": "Zona da Mata",
    "lagoa dos gatos": "Zona da Mata",
    "correntes": "Zona da Mata",
    "angelim": "Zona da Mata",
    "capoeiras": "Zona da Mata",
    "aguas belas": "Zona da Mata",
    "bom conselho": "Zona da Mata",
    "canhotinho": "Zona da Mata",
    "paranatama": "Zona da Mata",
    "terezinha": "Zona da Mata",
    "vicencia": "Zona da Mata",
    "limoeiro": "Zona da Mata",
    "timbauba": "Zona da Mata",
    "nazare da mata": "Zona da Mata",
    "tracunhaem": "Zona da Mata",
    "carpina": "Zona da Mata",
    "paudalho": "Zona da Mata",
    "buenos aires": "Zona da Mata",
    "alianca": "Zona da Mata",
    "condado": "Zona da Mata",
    "itaquitinga": "Zona da Mata",
    "ferreiros": "Zona da Mata",
    "machados": "Zona da Mata",
    "joao alfredo": "Zona da Mata",
    "passira": "Zona da Mata",
    "feira nova": "Zona da Mata",
    "cumaru": "Zona da Mata",
    "pocao": "Zona da Mata",
    "sao caitano": "Zona da Mata",
    "brejo da madre de deus": "Zona da Mata",
    "tacaimbo": "Zona da Mata",

    # Agreste
    "caruaru": "Agreste",
    "bezerros": "Agreste",
    "gravatá": "Agreste",
    "gravata": "Agreste",
    "santa cruz do capibaribe": "Agreste",
    "toritama": "Agreste",
    "surubim": "Agreste",
    "vertentes": "Agreste",
    "belo jardim": "Agreste",
    "cachoeirinha": "Agreste",
    "casinhas": "Agreste",
    "santa maria do cambuca": "Agreste",
    "frei miguelinho": "Agreste",
    "riacho das almas": "Agreste",
    "sao joaquim do monte": "Agreste",
    "altinho": "Agreste",
    "aguas vermelhas": "Agreste",
    "panelas": "Agreste",
    "cupira": "Agreste",
    "pesqueira": "Agreste",
    "pocos": "Agreste",
    "alagoinha": "Agreste",
    "sanharó": "Agreste",
    "sanharo": "Agreste",
    "pedra": "Agreste",
    "venturosa": "Agreste",
    "garanhuns": "Agreste",
    "lagoa do ouro": "Agreste",
    "sao joao": "Agreste",
    "palmeirina": "Agreste",
    "lajedo": "Agreste",
    "ibirajuba": "Agreste",
    "jupi": "Agreste",
    "buique": "Agreste",
    "tupanatinga": "Agreste",
    "iati": "Agreste",
    "itaiba": "Agreste",
    "sao bento do una": "Agreste",
    "tacaimbó": "Agreste",
    "ipe": "Agreste",

    # São Francisco
    "petrolina": "São Francisco",
    "salgueiro": "São Francisco",
    "araripina": "São Francisco",
    "ouricuri": "São Francisco",
    "santa maria da boa vista": "São Francisco",
    "floresta": "São Francisco",
    "serrita": "São Francisco",
    "verdejante": "São Francisco",
    "mirandiba": "São Francisco",
    "betania": "São Francisco",
    "terra nova": "São Francisco",
    "orobo": "São Francisco",
    "cabrobo": "São Francisco",
    "belem de sao francisco": "São Francisco",
    "itacuruba": "São Francisco",
    "jati": "São Francisco",
    "dormentes": "São Francisco",
    "lagoa grande": "São Francisco",
    "afrânio": "São Francisco",
    "afranio": "São Francisco",
    "oroco": "São Francisco",

    # Sertão 
    "serra talhada": "Sertão",
    "afogados da ingazeira": "Sertão",
    "iguaracy": "Sertão",
    "tuparetama": "Sertão",
    "carnaiba": "Sertão",
    "tabira": "Sertão",
    "brejinho": "Sertão",
    "santa terezinha": "Sertão",
    "flores": "Sertão",
    "boa vista": "Sertão",
    "sao jose do egito": "Sertão",
    "inaja": "Sertão",
    "ibimirim": "Sertão",
    "paraopeba": "Sertão",
    "tacaratu": "Sertão",
    "jatoba": "Sertão",
    "petrolândia": "Sertão",
    "petrolandia": "Sertão",
    "itaparica": "Sertão",
    "trindade": "Sertão",
    "exu": "Sertão",
    "moreilândia": "Sertão",
    "moreilandia": "Sertão",
    "granito": "Sertão",
    "ipubi": "Sertão",
    "bodoco": "Sertão",
    "santa filomena": "Sertão",
    "cedro": "Sertão",
    "belem do sao francisco": "Sertão",
    "custodia": "Sertão",
    "sertania": "Sertão",
    "arcoverde": "Sertão",
    "manari": "Sertão",
    "iguaraci": "Sertão",
    "itapetim": "Sertão",
}


def normalizar(texto: str) -> str:
    """Remove acentos e converte para minúsculas para comparação."""
    import unicodedata
    return unicodedata.normalize("NFD", texto).encode("ascii", "ignore").decode("ascii").lower().strip()


def municipio_para_regiao(cidade: str) -> str:
    """
    Retorna a região de PE correspondente ao município.
    Retorna 'Fora do Estado' se o município não for encontrado no mapeamento.
    """
    return MUNICIPIO_PARA_REGIAO.get(normalizar(cidade), "Fora do Estado")
