"""Criacao inicial limpa

Revision ID: 30a069b91f81
Revises: 
Create Date: 2026-06-27 20:46:01.922377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a069b91f81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exames',
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index(op.f('ix_exames_codigo'), 'exames', ['codigo'], unique=False)
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('is_administrador', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_funcionarios_id'), 'funcionarios', ['id'], unique=False)
    op.create_table('pacientes',
    sa.Column('prontuario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('prontuario')
    )
    op.create_index(op.f('ix_pacientes_prontuario'), 'pacientes', ['prontuario'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('groups', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('solicitacoes',
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('data_retorno', sa.Date(), nullable=True),
    sa.Column('unidade_solicitante', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_index(op.f('ix_solicitacoes_codigo'), 'solicitacoes', ['codigo'], unique=False)
    op.create_table('exames_solicitados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao', sa.Integer(), nullable=False),
    sa.Column('exame', sa.String(), nullable=False),
    sa.Column('paciente_solicitante', sa.Integer(), nullable=False),
    sa.Column('funcionario_atribuido', sa.Integer(), nullable=True),
    sa.Column('status_atribuicao', sa.String(), nullable=True),
    sa.Column('data_atribuicao', sa.Date(), nullable=True),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('detalhes', sa.String(), nullable=True),
    sa.Column('data_solicitacao', sa.Date(), nullable=False),
    sa.Column('data_conclusao', sa.Date(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exame'], ['exames.codigo'], ),
    sa.ForeignKeyConstraint(['funcionario_atribuido'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_solicitante'], ['pacientes.prontuario'], ),
    sa.ForeignKeyConstraint(['solicitacao'], ['solicitacoes.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exames_solicitados_id'), 'exames_solicitados', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exames_solicitados_id'), table_name='exames_solicitados')
    op.drop_table('exames_solicitados')
    op.drop_index(op.f('ix_solicitacoes_codigo'), table_name='solicitacoes')
    op.drop_table('solicitacoes')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_pacientes_prontuario'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_funcionarios_id'), table_name='funcionarios')
    op.drop_table('funcionarios')
    op.drop_index(op.f('ix_exames_codigo'), table_name='exames')
    op.drop_table('exames')
    # ### end Alembic commands ###
