import type { AgendamentoItem, MinhaAreaItem } from './types';

export const AGENDAMENTOS_MOCK: Omit<AgendamentoItem, 'regiao'>[] = [
  {
    id: 1,
    nome: 'Maria das Graças Silva',
    prontuario: '0482175',
    numeroSolicitacao: '0001',
    exame: 'TCABI',
    diasNaFila: 5,
    status: 'ALTA',
    unidadeSolicitante: 'Hospital Barão de Lucena',
    dataRetorno: '15/07/2026',
    localizacao: 'Recife',
    idade: 63,
    telefone: '(81) 99812-3456',
  },
  {
    id: 2,
    nome: 'José Carlos de Almeida',
    prontuario: '0391488',
    numeroSolicitacao: '0002',
    exame: 'ECO',
    diasNaFila: 12,
    status: 'ALTA',
    unidadeSolicitante: 'UPA Caruaru',
    dataRetorno: '02/08/2026',
    localizacao: 'Caruaru',
    idade: 47,
    telefone: '(81) 99734-5678',
  },
  {
    id: 3,
    nome: 'Ana Beatriz Nascimento',
    prontuario: '0510023',
    numeroSolicitacao: '0003',
    exame: 'RXMM1',
    diasNaFila: 3,
    status: 'ALTA',
    unidadeSolicitante: 'Policlínica Lessa de Andrade',
    dataRetorno: '20/07/2026',
    localizacao: 'Olinda',
    idade: 52,
    telefone: '(81) 98645-1234',
  },
  {
    id: 4,
    nome: 'Pedro Henrique Souza',
    prontuario: '0467790',
    numeroSolicitacao: '0004',
    exame: 'EDA',
    diasNaFila: 8,
    status: 'ALTA',
    unidadeSolicitante: 'Hospital Regional do Sertão',
    dataRetorno: '28/07/2026',
    localizacao: 'Petrolina',
    idade: 34,
    telefone: '(87) 99921-7890',
  },
  {
    id: 5,
    nome: 'Lucas Ferreira Lima',
    prontuario: '0523911',
    numeroSolicitacao: '0005',
    exame: 'RXPAP',
    diasNaFila: 1,
    status: 'ALTA',
    unidadeSolicitante: 'UBS Carpina',
    dataRetorno: '10/08/2026',
    localizacao: 'Carpina',
    idade: 16,
    telefone: '(81) 99456-3210',
  },
  {
    id: 6,
    nome: 'Francisca Oliveira Santos',
    prontuario: '0408265',
    numeroSolicitacao: '0006',
    exame: 'USABT',
    diasNaFila: 21,
    status: 'ALTA',
    unidadeSolicitante: 'Hospital de Vitória de Santo Antão',
    dataRetorno: '05/08/2026',
    localizacao: 'Vitória de Santo Antão',
    idade: 71,
    telefone: '(81) 98567-4321',
  },
];

export const MINHA_AREA_MOCK: Omit<MinhaAreaItem, 'regiao'>[] = [
  {
    id: 101,
    nome: 'Antônio Marcos Pereira',
    prontuario: '0399104',
    numeroSolicitacao: '0101',
    exame: 'TCTX1',
    diasNaFila: 4,
    status: 'ALTA',
    unidadeSolicitante: 'UPA Caruaru',
    dataRetorno: '18/07/2026',
    localizacao: 'Caruaru',
    idade: 58,
    telefone: '(81) 99678-5432',
    estado: 'EM_ANDAMENTO',
  },
  {
    id: 102,
    nome: 'Juliana Costa Barbosa',
    prontuario: '0512388',
    numeroSolicitacao: '0102',
    exame: 'TCAVT',
    diasNaFila: 6,
    status: 'ALTA',
    unidadeSolicitante: 'Hospital Barão de Lucena',
    dataRetorno: '22/07/2026',
    localizacao: 'Recife',
    idade: 41,
    telefone: '(81) 98789-6543',
    estado: 'EM_ANDAMENTO',
  },
  {
    id: 103,
    nome: 'Roberto Cavalcanti Melo',
    prontuario: '0445170',
    numeroSolicitacao: '0103',
    exame: 'EDA',
    diasNaFila: 9,
    status: 'ALTA',
    unidadeSolicitante: 'Hospital Regional do Sertão',
    dataRetorno: '25/07/2026',
    localizacao: 'Serra Talhada',
    idade: 60,
    telefone: '(87) 99890-7654',
    estado: 'AGUARDANDO_CONFIRMACAO',
  },
  {
    id: 104,
    nome: 'Camila Rodrigues Alves',
    prontuario: '0530742',
    numeroSolicitacao: '0104',
    exame: 'RXMM1',
    diasNaFila: 2,
    status: 'ALTA',
    unidadeSolicitante: 'Policlínica Lessa de Andrade',
    dataRetorno: '30/07/2026',
    localizacao: 'Nazaré da Mata',
    idade: 49,
    telefone: '(81) 99901-8765',
    estado: 'AGUARDANDO_CONFIRMACAO',
  },
  {
    id: 105,
    nome: 'Severino Bezerra da Mota',
    prontuario: '0376519',
    numeroSolicitacao: '0105',
    exame: 'CLN',
    diasNaFila: 0,
    status: 'ALTA',
    unidadeSolicitante: 'UBS Garanhuns',
    dataRetorno: '12/07/2026',
    localizacao: 'Garanhuns',
    idade: 67,
    telefone: '(87) 98012-9876',
    estado: 'CONFIRMADO',
  },
  {
    id: 106,
    nome: 'Patrícia Gomes da Silva',
    prontuario: '0498003',
    numeroSolicitacao: '0106',
    exame: 'CLN',
    diasNaFila: 0,
    status: 'ALTA',
    unidadeSolicitante: 'Hospital de Vitória de Santo Antão',
    dataRetorno: '08/07/2026',
    localizacao: 'Vitória de Santo Antão',
    idade: 38,
    telefone: '(81) 99123-0987',
    estado: 'PROBLEMA_REPORTADO',
  },
];
