/**
 * Dados de exemplo(enquanto a api está em desenvolvimento).
 *
 * A região (mesorregião) de cada paciente é derivada automaticamente
 * a partir da localizacao via API do IBGE, por isso não está presente
 * nos mocks. A store preenche esse campo ao carregar os dados.
 */
import type { AgendamentoItem, MinhaAreaItem } from './types';

// colocamos esse omit, pois ele representa um tipo de agendamento que não tem a propriedade "regiao"
// pois será calculado depois
export const AGENDAMENTOS_MOCK: Omit<AgendamentoItem, 'regiao'>[] = [
  {
    id: 1,
    nome: 'Maria das Graças Silva',
    prontuario: '0482175',
    exames: ['Tomografia', 'Ultrassonografia'],
    diasNaFila: 5,
    status: 'ALTA',
    unidadeSolicitante: 'Hospital Barão de Lucena',
    dataRetorno: '15/07/2026',
    localizacao: 'Recife',
    idade: 63,
  },
  {
    id: 2,
    nome: 'José Carlos de Almeida',
    prontuario: '0391488',
    exames: ['Ressonância'],
    diasNaFila: 12,
    status: 'ALTA',
    unidadeSolicitante: 'UPA Caruaru',
    dataRetorno: '02/08/2026',
    localizacao: 'Caruaru',
    idade: 47,
  },
  {
    id: 3,
    nome: 'Ana Beatriz Nascimento',
    prontuario: '0510023',
    exames: ['Mamografia'],
    diasNaFila: 3,
    status: 'ALTA',
    unidadeSolicitante: 'Policlínica Lessa de Andrade',
    dataRetorno: '20/07/2026',
    localizacao: 'Olinda',
    idade: 52,
  },
  {
    id: 4,
    nome: 'Pedro Henrique Souza',
    prontuario: '0467790',
    exames: ['Endoscopia', 'Colonoscopia'],
    diasNaFila: 8,
    status: 'ALTA',
    unidadeSolicitante: 'Hospital Regional do Sertão',
    dataRetorno: '28/07/2026',
    localizacao: 'Petrolina',
    idade: 34,
  },
  {
    id: 5,
    nome: 'Lucas Ferreira Lima',
    prontuario: '0523911',
    exames: ['Espirometria'],
    diasNaFila: 1,
    status: 'ALTA',
    unidadeSolicitante: 'UBS Carpina',
    dataRetorno: '10/08/2026',
    localizacao: 'Carpina',
    idade: 16,
  },
  {
    id: 6,
    nome: 'Francisca Oliveira Santos',
    prontuario: '0408265',
    exames: ['Ultrassonografia', 'Tomografia'],
    diasNaFila: 21,
    status: 'ALTA',
    unidadeSolicitante: 'Hospital de Vitória de Santo Antão',
    dataRetorno: '05/08/2026',
    localizacao: 'Vitória de Santo Antão',
    idade: 71,
  },
];

export const MINHA_AREA_MOCK: Omit<MinhaAreaItem, 'regiao'>[] = [
  {
    id: 101,
    nome: 'Antônio Marcos Pereira',
    prontuario: '0399104',
    exames: ['Tomografia'],
    diasNaFila: 4,
    status: 'ALTA',
    unidadeSolicitante: 'UPA Caruaru',
    dataRetorno: '18/07/2026',
    localizacao: 'Caruaru',
    idade: 58,
    estado: 'EM_ANDAMENTO',
  },
  {
    id: 102,
    nome: 'Juliana Costa Barbosa',
    prontuario: '0512388',
    exames: ['Ressonância', 'Ultrassonografia'],
    diasNaFila: 6,
    status: 'ALTA',
    unidadeSolicitante: 'Hospital Barão de Lucena',
    dataRetorno: '22/07/2026',
    localizacao: 'Recife',
    idade: 41,
    estado: 'EM_ANDAMENTO',
  },
  {
    id: 103,
    nome: 'Roberto Cavalcanti Melo',
    prontuario: '0445170',
    exames: ['Endoscopia'],
    diasNaFila: 9,
    status: 'ALTA',
    unidadeSolicitante: 'Hospital Regional do Sertão',
    dataRetorno: '25/07/2026',
    localizacao: 'Serra Talhada',
    idade: 60,
    estado: 'AGUARDANDO_CONFIRMACAO',
  },
  {
    id: 104,
    nome: 'Camila Rodrigues Alves',
    prontuario: '0530742',
    exames: ['Mamografia'],
    diasNaFila: 2,
    status: 'ALTA',
    unidadeSolicitante: 'Policlínica Lessa de Andrade',
    dataRetorno: '30/07/2026',
    localizacao: 'Nazaré da Mata',
    idade: 49,
    estado: 'AGUARDANDO_CONFIRMACAO',
  },
  {
    id: 105,
    nome: 'Severino Bezerra da Mota',
    prontuario: '0376519',
    exames: ['Espirometria'],
    diasNaFila: 0,
    status: 'ALTA',
    unidadeSolicitante: 'UBS Garanhuns',
    dataRetorno: '12/07/2026',
    localizacao: 'Garanhuns',
    idade: 67,
    estado: 'FINALIZADO',
    resultado: 'CONFIRMADO',
  },
  {
    id: 106,
    nome: 'Patrícia Gomes da Silva',
    prontuario: '0498003',
    exames: ['Colonoscopia'],
    diasNaFila: 0,
    status: 'ALTA',
    unidadeSolicitante: 'Hospital de Vitória de Santo Antão',
    dataRetorno: '08/07/2026',
    localizacao: 'Vitória de Santo Antão',
    idade: 38,
    estado: 'FINALIZADO',
    resultado: 'CANCELADO',
  },
];
