import type { AgendamentoItem } from '../funcionario/types';
import type {
  AgendamentoGerenciamento,
  AgendamentoRemovido,
  Funcionario,
  PendenciaItem,
  VisaoGeral,
} from './types';

export const MOCK_FUNCIONARIOS: Funcionario[] = [
  { username: 'fabiana.lopes', nome: 'Fabiana Lopes' },
  { username: 'joao.silva', nome: 'João Silva' },
  { username: 'carla.mendes', nome: 'Carla Mendes' },
  { username: 'ricardo.alves', nome: 'Ricardo Alves' },
];

export const MOCK_VISAO_GERAL: VisaoGeral = {
  kpis: [
    { id: 'media_card_funcionario', label: 'Média de Exames por Funcionário', valor: 3.5, categoria: 'principal' },
    { id: 'media_exames_agendados', label: 'Média de Exames Agendados', valor: 4.0, tendencia: 5, categoria: 'principal' },
    { id: 'quantidade_funcionarios', label: 'Quantidade de Funcionários', valor: 4, categoria: 'principal' },
    { id: 'total_cards', label: 'Total de Exames', valor: 14, categoria: 'principal' },
    { id: 'tempo_medio_atendimento', label: 'Tempo médio de atendimento', valor: 3.8, sufixo: 'dias', categoria: 'extra' },
    { id: 'solicitacoes_atendidas', label: 'Solicitações atendidas', valor: 367, categoria: 'extra' },
    { id: 'pacientes_devolvidos_fila', label: 'Pacientes devolvidos à fila', valor: 55, tendencia: 15, categoria: 'extra' },
  ],
  graficos: [
    {
      id: 'por_tipo_exame',
      titulo: 'Por tipo de exame',
      subtitulo: 'Acompanhe a distribuição dos exames por tipo',
      tipo: 'barras_horizontais',
      categoria: 'principal',
      dados: [
        { categoria: 'Colonoscopia', agendados: 8, emAndamento: 2, aAgendar: 0 },
        { categoria: 'Endoscopia', agendados: 4, emAndamento: 6, aAgendar: 1 },
        { categoria: 'Ultrassonografia', agendados: 3, emAndamento: 0, aAgendar: 2 },
        { categoria: 'Mamografia', agendados: 1, emAndamento: 1, aAgendar: 0 },
        { categoria: 'Espirometria', agendados: 0, emAndamento: 1, aAgendar: 0 },
      ],
    },
    {
      id: 'por_localidade',
      titulo: 'Por localidade',
      subtitulo: 'Entenda como os exames se distribuem por localidade',
      tipo: 'barras_horizontais',
      categoria: 'principal',
      dados: [
        { categoria: 'Olinda', agendados: 0, emAndamento: 8, aAgendar: 2 },
        { categoria: 'Recife', agendados: 4, emAndamento: 0, aAgendar: 5 },
        { categoria: 'Jaboatão dos Guararapes', agendados: 0, emAndamento: 2, aAgendar: 1 },
        { categoria: 'Caruaru', agendados: 1, emAndamento: 1, aAgendar: 0 },
        { categoria: 'Petrolina', agendados: 1, emAndamento: 0, aAgendar: 0 },
      ],
    },
    {
      id: 'problemas_reportados',
      titulo: 'Problemas reportados',
      subtitulo: 'Quantitativo de problemas reportados',
      tipo: 'barras_verticais',
      categoria: 'principal',
      dados: [
        { motivo: 'Paciente não respondeu', quantidade: 99 },
        { motivo: 'Dados inconsistentes', quantidade: 74 },
        { motivo: 'Duplicidade', quantidade: 95 },
        //{ motivo: 'Erro cadastral', quantidade: 24 },
      ],
    },
  ],
};

export const MOCK_PENDENCIAS: PendenciaItem[] = [
  {
    id: 202,
    nome: 'Marlene Tavares de Lima',
    prontuario: '000777888',
    solicitacao: '0202',
    exame: 'USABT',
    diasNaFila: 9,
    status: 'MÉDIA',
    unidadeSolicitante: 'Policlínica Lessa de Andrade',
    dataRetorno: '18/07/2026',
    localizacao: 'Recife',
    regiao: 'Região Metropolitana',
    idade: 54,
    telefone: '(81) 98812-3344',
    problema_motivo: 'Paciente não respondeu aos contatos',
    problema_detalhes: 'Três tentativas de ligação sem retorno nos últimos 5 dias.',
    responsavel: 'carla.mendes',
  },
];

export const MOCK_GERENCIAMENTO_ANDAMENTO: AgendamentoGerenciamento[] = [
  {
    id: 301,
    nome: 'Gisela Maria Santos',
    prontuario: '000333222',
    solicitacao: '0301',
    exame: 'ECO',
    diasNaFila: 22,
    status: 'MÉDIA',
    unidadeSolicitante: 'UBS Boa Vista',
    dataRetorno: '05/08/2026',
    localizacao: 'Recife',
    regiao: 'Região Metropolitana',
    idade: 41,
    telefone: '(81) 98456-7890',
    estado: 'EM_ANDAMENTO',
    responsavel: 'joao.silva',
  },
];

export const MOCK_GERENCIAMENTO_CONCLUIDO: AgendamentoGerenciamento[] = [
  {
    id: 302,
    nome: 'Severino Ramos da Silva',
    prontuario: '000111999',
    solicitacao: '0302',
    exame: 'EDA',
    diasNaFila: 45,
    status: 'ALTA',
    unidadeSolicitante: 'UBS Centro - Caruaru',
    dataRetorno: '12/07/2026',
    localizacao: 'Caruaru',
    regiao: 'Agreste',
    idade: 69,
    telefone: '(81) 99567-8901',
    estado: 'CONFIRMADO',
    responsavel: 'carla.mendes',
  },
  {
    id: 303,
    nome: 'Lúcia Helena Ferreira',
    prontuario: '000222888',
    solicitacao: '0303',
    exame: 'RXMM1',
    diasNaFila: 28,
    status: 'MÉDIA',
    unidadeSolicitante: 'UBS Boa Viagem',
    dataRetorno: '08/07/2026',
    localizacao: 'Recife',
    regiao: 'Região Metropolitana',
    idade: 56,
    telefone: '(81) 98234-5678',
    estado: 'PROBLEMA_REPORTADO',
    responsavel: 'fabiana.lopes',
    problema_motivo: 'Dados inconsistentes',
    problema_detalhes: 'O prontuário do paciente apresenta divergência entre o nome registrado e o documento de identidade apresentado.',
  },
];

export const MOCK_REMOVIDOS: AgendamentoRemovido[] = [
  {
    id: 401,
    nome: 'Tereza Cristina Barros',
    prontuario: '000888777',
    solicitacao: '0401',
    exame: 'RXMM1',
    diasNaFila: 30,
    status: 'MÉDIA',
    unidadeSolicitante: 'UBS Boa Viagem',
    dataRetorno: '01/07/2026',
    localizacao: 'Recife',
    regiao: 'Região Metropolitana',
    idade: 55,
    telefone: '(81) 98678-9012',
    responsavel: 'ricardo.alves',
    problema_motivo: 'Dados inconsistentes',
    problema_detalhes: 'CPF do paciente diverge do cadastro no sistema.',
  },
  {
    id: 402,
    nome: 'Francisco Almeida Neto',
    prontuario: '000666555',
    solicitacao: '0402',
    exame: 'USABT',
    diasNaFila: 18,
    status: 'BAIXA',
    unidadeSolicitante: 'UBS Carpina',
    dataRetorno: '08/07/2026',
    localizacao: 'Carpina',
    regiao: 'Mata Norte',
    idade: 43,
    telefone: '(81) 99789-0123',
    responsavel: 'fabiana.lopes',
    problema_motivo: 'Paciente não respondeu',
    problema_detalhes: 'Três tentativas de contato telefônico sem sucesso.',
  },
];

export const MOCK_FILA_ADMIN: AgendamentoItem[] = [
  {
    id: 1,
    nome: 'Maria das Graças Oliveira',
    prontuario: '000123456',
    solicitacao: '0501',
    exame: 'TCABC',
    diasNaFila: 42,
    status: 'ALTA',
    unidadeSolicitante: 'UBS Centro - Caruaru',
    dataRetorno: '15/07/2026',
    localizacao: 'Caruaru',
    regiao: 'Agreste',
    idade: 67,
    telefone: '(81) 98890-1234',
  },
];
