import type { AgendamentoItem } from '../funcionario/types';
import type {
  AgendamentoGerenciamento,
  AgendamentoRemovido,
  Funcionario,
  PendenciaItem,
} from './types';

export const MOCK_FUNCIONARIOS: Funcionario[] = [
  { username: 'fabiana.lopes', nome: 'Fabiana Lopes' },
  { username: 'joao.silva', nome: 'João Silva' },
  { username: 'carla.mendes', nome: 'Carla Mendes' },
  { username: 'ricardo.alves', nome: 'Ricardo Alves' },
];

export const MOCK_PENDENCIAS: PendenciaItem[] = [
  {
    id: 202,
    nome: 'Marlene Tavares de Lima',
    prontuario: '000777888',
    solicitacao: '0202',
    exame: 'USABT',
    diasNaFila: 9,
    status: 'MÉDIA',
    unidadeSolicitante: 'Policlínica Lessa de Andrade',
    dataRetorno: '18/07/2026',
    localizacao: 'Recife',
    regiao: 'Região Metropolitana',
    idade: 54,
    telefone: '(81) 98812-3344',
    problema_motivo: 'Paciente não respondeu aos contatos',
    problema_detalhes: 'Três tentativas de ligação sem retorno nos últimos 5 dias.',
    responsavel: 'carla.mendes',
  },
];

export const MOCK_GERENCIAMENTO_ANDAMENTO: AgendamentoGerenciamento[] = [
  {
    id: 301,
    nome: 'Gisela Maria Santos',
    prontuario: '000333222',
    solicitacao: '0301',
    exame: 'ECO',
    diasNaFila: 22,
    status: 'MÉDIA',
    unidadeSolicitante: 'UBS Boa Vista',
    dataRetorno: '05/08/2026',
    localizacao: 'Recife',
    regiao: 'Região Metropolitana',
    idade: 41,
    telefone: '(81) 98456-7890',
    estado: 'EM_ANDAMENTO',
    responsavel: 'joao.silva',
  },
];

export const MOCK_GERENCIAMENTO_CONCLUIDO: AgendamentoGerenciamento[] = [
  {
    id: 302,
    nome: 'Severino Ramos da Silva',
    prontuario: '000111999',
    solicitacao: '0302',
    exame: 'EDA',
    diasNaFila: 45,
    status: 'ALTA',
    unidadeSolicitante: 'UBS Centro - Caruaru',
    dataRetorno: '12/07/2026',
    localizacao: 'Caruaru',
    regiao: 'Agreste',
    idade: 69,
    telefone: '(81) 99567-8901',
    estado: 'CONFIRMADO',
    responsavel: 'carla.mendes',
  },
  {
    id: 303,
    nome: 'Lúcia Helena Ferreira',
    prontuario: '000222888',
    solicitacao: '0303',
    exame: 'RXMM1',
    diasNaFila: 28,
    status: 'MÉDIA',
    unidadeSolicitante: 'UBS Boa Viagem',
    dataRetorno: '08/07/2026',
    localizacao: 'Recife',
    regiao: 'Região Metropolitana',
    idade: 56,
    telefone: '(81) 98234-5678',
    estado: 'PROBLEMA_REPORTADO',
    responsavel: 'fabiana.lopes',
    problema_motivo: 'Dados inconsistentes',
    problema_detalhes: 'O prontuário do paciente apresenta divergência entre o nome registrado e o documento de identidade apresentado.',
  },
];

export const MOCK_REMOVIDOS: AgendamentoRemovido[] = [
  {
    id: 401,
    nome: 'Tereza Cristina Barros',
    prontuario: '000888777',
    solicitacao: '0401',
    exame: 'RXMM1',
    diasNaFila: 30,
    status: 'MÉDIA',
    unidadeSolicitante: 'UBS Boa Viagem',
    dataRetorno: '01/07/2026',
    localizacao: 'Recife',
    regiao: 'Região Metropolitana',
    idade: 55,
    telefone: '(81) 98678-9012',
    responsavel: 'ricardo.alves',
    problema_motivo: 'Dados inconsistentes',
    problema_detalhes: 'CPF do paciente diverge do cadastro no sistema.',
  },
  {
    id: 402,
    nome: 'Francisco Almeida Neto',
    prontuario: '000666555',
    solicitacao: '0402',
    exame: 'USABT',
    diasNaFila: 18,
    status: 'BAIXA',
    unidadeSolicitante: 'UBS Carpina',
    dataRetorno: '08/07/2026',
    localizacao: 'Carpina',
    regiao: 'Mata Norte',
    idade: 43,
    telefone: '(81) 99789-0123',
    responsavel: 'fabiana.lopes',
    problema_motivo: 'Paciente não respondeu',
    problema_detalhes: 'Três tentativas de contato telefônico sem sucesso.',
  },
];

export const MOCK_FILA_ADMIN: AgendamentoItem[] = [
  {
    id: 501,
    nome: 'Maria das Graças Oliveira',
    prontuario: '000123456',
    solicitacao: '0501',
    exame: 'TCABC',
    diasNaFila: 42,
    status: 'ALTA',
    unidadeSolicitante: 'UBS Centro - Caruaru',
    dataRetorno: '15/07/2026',
    localizacao: 'Caruaru',
    regiao: 'Agreste',
    idade: 67,
    telefone: '(81) 98890-1234',
  },
];
